name: demo

on:
  push:
    branches: [ master, proposals ]
  pull_request:
    branches: [ master, proposals ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Vercel Action
        uses: amondnet/vercel-action@v20.0.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-comment: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-deployment: true
          vercel-project-name: bubbles
