name: prod

on:
  push:
    branches: [ master ]

jobs:
  deploy-demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy Demo 
        uses: amondnet/vercel-action@v20.0.0
        with:
          vercel-project-name: bubbles-demo
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_DEMO_PROJECT_ID }}
          vercel-args: '--prod'
          github-deployment: true

  deploy-proposals:    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy Proposals
      uses: amondnet/vercel-action@v20.0.0
      with:
        vercel-project-name: bubble-proposals
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROPOSALS_PROJECT_ID }}
        vercel-args: '--prod'
